version: "3.7"

services:
  web_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: containerwill
    restart: always
    ports:
      - 8050:80
    networks:
      app_network_prueba:
        aliases:
          - app_host_prueba
    depends_on:
      - databaseonil

  databaseonil:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2171805
      POSTGRES_USER: 2171805
      POSTGRES_DB: dbOnil
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      app_network_prueba:
        aliases:
          - data_host_prueba

volumes:
  pgdata:
networks:
  app_network_prueba:
    name: dbOnil
    driver: bridge
    ipam:
      driver: default
